name: Test Project

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.160.1'
          extended: true

      - name: Build site
        run: hugo
        working-directory: ./darktheme

      - name: Check if index.html exists
        run: test -f ./darktheme/public/index.html
